version: "3.7"
services:
  bento:
    image: ${REGISTRY}/${APP}:${APP_VERSION}dev
    environment:
      DEV: "True"
      LOGLEVEL_NAME: "10"
    volumes:
      - ${HOME}/${BENTOREPO}/bento/:${PYTHON_SP}/bento/
    # Override the gunicorn default command
    # command: ["python3", "-m", "bento.develop"]
    command: ["python3", "-m", "entrypoint"]
