version: "3.7"
services:
  bento:
    image: ${REGISTRY}/${APP}:${APP_VERSION}dev
    environment:
      DEV: "True"
      LOGLEVEL_NAME: "10"
    volumes:
      - ${HOME}/${BUILDER_REPO}/${APP}/:/app/${APP}/
      # You may find it useful to mount and edit the Bento codebase
      # - ${HOME}/${BENTOREPO}/bento/:${PYTHON_SP}/bento/
    # Override the gunicorn default command
    command: ["python3", "-m", "entrypoint"]
