version: "3.7"
services:
  bento:
    image: ${REGISTRY}/${APP}:${APP_VERSION}
    env_file:
      - .env
    environment:
      APP: ${APP}
      APP_HOME: /app
    # When you have data to mount, uncomment this and double-check your ENV file
    # volumes:
      # - ${HOME}/${VOLUMES}/${DATA_DIR}/:/app/${DATA_DIR}/
    ports:
      - "${BENTO_PORT}:${BENTO_PORT}"
