version: "3.7"
services:
  bento:
    image: ${REGISTRY}/${APP}:${APP_VERSION}
    env_file:
      - .env
    environment:
      APP: ${APP}
      APP_HOME: /app
    volumes:
      - ${HOME}/${VOLUMES}/data/:/app/${DATA_DIR}/
      - ${HOME}/${VOLUMES}/storage/:/app/${STORAGE_DIR}/
    ports:
      - "${BENTO_PORT}:${BENTO_PORT}"
